### ISSUE TITLE
No French translation

### ISSUE THREAD

**Issue by ghost** [tim-sueberkrueb/crazy-mark#1]
Thanks for your amazing work!
I have done a proposal of translation in French in [Transifex](https://www.transifex.com/tim-sueberkrueb/crazy-mark/translate/), could you import it?
Have you ever considered to host the translations in [Launchpad](https://wiki.ubuntu.com/Translations/LpProjectConfiguration), this way the translations could be more easily reviewed by Ubuntu Translators?

**Comment by timsueberkrueb** [comment]
@Anne017 thanks very much for your contribution!
I'll update the app with your translation.

>  Have you ever considered to host the translations in Launchpad, this way the translations could be more easily reviewed by Ubuntu Translators?

I'm not a big fan of the Launchpad translation features to be honest, I'd like to stick with Transifex.

**Comment by timsueberkrueb** [comment]
App has been updated including your translations! Thanks @Anne017!
