### ISSUE TITLE
Tap to Move Cursor

### ISSUE THREAD

**Issue by Foggalong** [tim-sueberkrueb/crazy-mark#3]
Tap to move cursor is something that's really needed for the editor. Only being able to navigate using the keyboard is a real pain.

**Comment by timsueberkrueb** [comment]
Hey @Foggalong, thanks for opening an issue.
This should work on the phone/tablet (it works as expected at least on my BQ E4.5). I'm not sure right now if it works on the desktop, even though it definetly should :)
What device, Ubuntu version (desktop) or channel (mobile device: rc-proposed/stable) are you using?

**Comment by Foggalong** [comment]
This is the mobile stable version running on the BQ M10 with a hardware keyboard attached

**Comment by timsueberkrueb** [comment]
@Foggalong thanks. @mivoligo couldn't reproduce it. Are you running the latest OTA? If it still occurrs, can you possibly create a video of the problem?

**Comment by Foggalong** [comment]
@tim-sueberkrueb Yeah it's the latest OTA. I'll try and get a video with my phone or something, but as best as it can be summarised in case that doesn't work: touching somewhere in the editing part of the interface doesn't change the cursor location to that place and instead just keeps typing from wherever the cursor was. Moving the cursor with the directional hardware keyboard buttons however does change the location it types from.

**Comment by timsueberkrueb** [comment]
Is this still an issue?

**Comment by timsueberkrueb** [comment]
Please reopen in case this is still relevant :)
