### ISSUE TITLE
Xenial - feature request

### ISSUE THREAD

**Issue by 3arn0wl** [tim-sueberkrueb/crazy-mark#6]
Hi

I LOVE Crazy Mark, and use it on UT quite a bit, in my own not-really-a-techie-sort-of-way.

I would love to see it available for UT Xenial, if that's possible.

Thanks again for the app! :)

**Comment by timsueberkrueb** [comment]
Thanks :)
Yep, will update it.

**Comment by 3arn0wl** [comment]
:) Thank you. 

On Monday, 27 August 2018 14:20:59 CDT, Tim Süberkrüb 
<notifications@github.com> wrote:
> Thanks :)
> Yep, will update it.
> 



-- 
Sent using Dekko from my Ubuntu device

**Comment by timsueberkrueb** [comment]
Update should land in the Open Store as soon as it gets approved :)

**Comment by 3arn0wl** [comment]
:) Excellent work! Thank you so much.

On Monday, 27 August 2018 15:33:52 CDT, Tim Süberkrüb 
<notifications@github.com> wrote:
> Update should land in the Open Store as soon as it gets approved :)
> 



-- 
Sent using Dekko from my Ubuntu device

**Comment by timsueberkrueb** [comment]
Glad you like it :)
